@startuml

'UML GENERE PAR CODE :)

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

PACKAGE western{
	CLASS Barman  extends Personnage {
		+<<create>>Barman(
		+<<create>>Barman(
		-bar
		-clients
	}


	CLASS Boisson  {
		-substantif
		+{static}EAU
		-{static}boissons
		-<<create>>Boisson(
	}
Boisson -- Substantif
Boisson -- Boisson


	CLASS Brigand  extends Personnage implements HorsLaLoi {
		#{static}LOOK_PAR_DEFAUT
		-look
		-recompense
		-estLibre
		-captives
		-gardien
		+<<create>>Brigand(
		+<<create>>Brigand(
		+<<create>>Brigand(
		-{static}boissonParDefaut
	}
Brigand -- Cowboy
Brigand -- Boisson


	CLASS Cowboy  extends Personnage {
		-gains
		-captures
		+<<create>>Cowboy(
		+<<create>>Cowboy(
		-{static}boissonParDefaut
	}
Cowboy -- Boisson


	CLASS Dame  extends Personnage {
		-estLibre
		-sauveur
		-ravisseur
		+<<create>>Dame(
		+<<create>>Dame(
		-{static}boissonParDefaut
	}
Dame -- Cowboy
Dame -- HorsLaLoi
Dame -- Boisson


	ENUM Genre<<enum>>{

	}

	CLASS Histoire4  {
		+<<create>>Histoire4(
	}


	CLASS Histoire5  {
		<<create>>Histoire5(
		luke
		averell
		scarlett
		narrateur
	}
Histoire5 -- Barman
Histoire5 -- Brigand
Histoire5 -- Ripou
Histoire5 -- Narrateur


	INTERFACE HorsLaLoi <<interface>>  implements Nommable{

	}

	CLASS Narrateur  extends Personnage {
		+<<create>>Narrateur(
		+<<create>>Narrateur(
	}


	INTERFACE Nommable <<interface>> {

	}

	CLASS Personnage  implements Nommable {
		-{static}BOISSON_PAR_DEFAUT
		-nom
		-boisson
		+<<create>>Personnage(
		+<<create>>Personnage(
	}
Personnage -- Boisson
Personnage -- Boisson


	CLASS Ripou  extends Cowboy implements HorsLaLoi {
		-brigand
		+<<create>>Ripou(
		+<<create>>Ripou(
		+<<create>>Ripou(
	}
Ripou -- Brigand


	CLASS Sherif  extends Cowboy {
		+<<create>>Sherif(
		+<<create>>Sherif(
		-wanted
		-ravisseur
		-captures
	}
Sherif -- HorsLaLoi


	CLASS Substantif  {
		-nom
		-genre
		+<<create>>Substantif(
	}
Substantif -- Genre



}
@enduml
