@startuml

'UML GENERE PAR CODE :)

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

PACKAGE pumlFromJava{
	CLASS Class{
		object
	}


	CLASS Field{
		methode
	}



	CLASS Java2Puml{
	}


	CLASS Package{
		pack
	}


	CLASS PumlDiagram{
		stringVal
	}


	CLASS PumlDoclet{
		fileName
		dir
		newPackage
		havePackage
	}





}


Java2Puml "appel Javadoc" -> PumlDoclet
PumlDoclet "recupere le package" --> Package
Package "recupere la class" --> Class
Class "recupere les --methode--" --> Field
'je sais que ça ne s'appel pas methode mais gros trou ed memoire
Java2Puml "Donne le fichier a ecrire,\n le directory et le nom du fichier" -l> PumlDiagram
@enduml