@startuml

'UML GENERE PAR CODE :)

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

PACKAGE pumlFromJava{
class PumlDiagram{
        StringVal
    }

    class Java2Puml{

    }
    class PumlDoclet {
        fileName
        dir
        doDCC
        doDCA
    }


    class Package{
        pack
    }

    class Class{
        object

    }

    class Field{
        methode

    }

    class Enum{
        object

    }

    class Interface{
        object
    }

    class Constructor{
        methode

    }

    class Methode{
        methode


    }

    class Modifier {
             modifiers
        }

    class Parameters {
        element

    }

PumlDoclet "recupère le package" --* Package

Package "récupère la class" o-- Class
Package "récupère l'interface" o-- Interface
Package "récupère l'enum" o-- Enum

Class  --> Field : récupère les \nvariables\n en global

PumlDoclet "Donne le fichier a ecrire,\n le directory et le nom du fichier" *---l- PumlDiagram

Class o-- Constructor : créé le constructeur
Class *-- Methode : récupère les \nméthodes\n de la class

Interface o-- Methode : récupère les \nméthodes\n de l'interface
Interface  o-- Field : récupère les \nvariables\n en global

Enum o-- Methode : récupère les \nméthodes \nde l'enum
Enum  o-- Field : récupère les \nvariables\n en global

Methode o-- Parameters : récupère les \nparamètres\nde chaque\n méthode

Methode *-- Modifier : récupère \nl'attribut\n de la méthode
Field *-- Modifier : récupère \nl'attribut \nde la variable

Modifier "*"-->"1" Modifier : -modifiers[]

}
@enduml